# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 18:06
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'menu item Translation',
                'db_table': 'multimenus_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_id',
            field=models.CharField(blank=True, help_text='Template tags refers to Menu ID.', max_length=255, verbose_name='Menu ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitemtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='multimenus.MenuItem'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
