# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 09:23
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.sites.models import Site
import django.db.models.deletion


def get_first_site_id():
    try:
        return Site.objects.all()[0].pk
    except Site.DoesNotExist:
        raise Exception("Multimenus required sites framework with at least one site added.")


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('multimenus', '0002_auto_20170420_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='site',
            field=models.ForeignKey(default=get_first_site_id, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
    ]
