# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimenus', '0003_menuitem_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('path',), 'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
    ]
